// Package grpcgateway builds a grpc-gateway as a plain http.Handler, so the
// JSON/HTTP transport runs as just another brick of the server kit — wrapped by
// httpserver and supervised in the same worker.Group as the gRPC and REST
// servers.
//
// The gateway translates RESTful JSON requests into gRPC calls against a backing
// gRPC server, using the handlers generated by protoc-gen-grpc-gateway from your
// google.api.http annotations. New dials that gRPC server (or reuses a
// connection you supply), creates a runtime.ServeMux, applies the generated
// registrars, and returns a *Gateway that embeds http.Handler.
//
// # Usage
//
//	gw, err := grpcgateway.New(ctx, grpcgateway.Config{
//		Endpoint: opts.GRPC.Addr, // the gRPC server this proxies to
//	}, widgetv1.RegisterWidgetServiceHandler)
//	if err != nil {
//		return err
//	}
//	closer.Add(gw.Close) // release the dialed conn on shutdown
//
//	group.Add(httpserver.New(httpserver.Config{
//		Name: "gateway-server", Addr: opts.Gateway.Addr, Logger: log.Slog(),
//	}, gw))
//
// Because gw is an http.Handler, cross-cutting behavior (tracing, request
// metrics, auth) is added the stdlib way — by wrapping it with middleware
// (the middleware package, otelhttp, ...) before handing it to httpserver.
//
// # Connection ownership
//
// When Config.ClientConn is nil, New dials Config.Endpoint and the Gateway owns
// that connection — call Close to release it. When you pass Config.ClientConn,
// New uses it as-is and Close is a no-op: the connection's lifecycle stays with
// you (e.g. managed by your DI container / closer).
//
// # Config
//
//   - Endpoint: gRPC target to proxy to; required unless ClientConn is set.
//   - ClientConn: reuse an existing *grpc.ClientConn instead of dialing.
//   - DialOptions: override the default insecure dial options.
//   - MuxOptions: forwarded to runtime.NewServeMux (marshaler, error handler,
//     header matchers, ...).
package grpcgateway
