// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/assanoff/skit/auditlog"
	"github.com/jmoiron/sqlx"
	"sync"
)

// Ensure, that StoreMock does implement auditlog.Store.
// If this is not the case, regenerate this file with moq.
var _ auditlog.Store = &StoreMock{}

// StoreMock is a mock implementation of auditlog.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked auditlog.Store
//		mockedStore := &StoreMock{
//			DeleteVersionsFunc: func(ctx context.Context, modelType string, modelID string, versions []int) (int, error) {
//				panic("mock out the DeleteVersions method")
//			},
//			OverThresholdFunc: func(ctx context.Context, threshold int, limit int) ([]auditlog.ModelRef, error) {
//				panic("mock out the OverThreshold method")
//			},
//			QueryHistoryByModelIDFunc: func(ctx context.Context, modelType string, modelID string) ([]auditlog.AuditLog, error) {
//				panic("mock out the QueryHistoryByModelID method")
//			},
//			QueryLastByModelIDFunc: func(ctx context.Context, modelType string, modelID string) (auditlog.AuditLog, error) {
//				panic("mock out the QueryLastByModelID method")
//			},
//			QueryModelByVersionFunc: func(ctx context.Context, modelType string, modelID string, ver int) (auditlog.AuditLog, error) {
//				panic("mock out the QueryModelByVersion method")
//			},
//			SaveFunc: func(ctx context.Context, al auditlog.AuditLog) error {
//				panic("mock out the Save method")
//			},
//			VersionsFunc: func(ctx context.Context, modelType string, modelID string) ([]int, error) {
//				panic("mock out the Versions method")
//			},
//			WithTxFunc: func(tx sqlx.ExtContext) auditlog.Store {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedStore in code that requires auditlog.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// DeleteVersionsFunc mocks the DeleteVersions method.
	DeleteVersionsFunc func(ctx context.Context, modelType string, modelID string, versions []int) (int, error)

	// OverThresholdFunc mocks the OverThreshold method.
	OverThresholdFunc func(ctx context.Context, threshold int, limit int) ([]auditlog.ModelRef, error)

	// QueryHistoryByModelIDFunc mocks the QueryHistoryByModelID method.
	QueryHistoryByModelIDFunc func(ctx context.Context, modelType string, modelID string) ([]auditlog.AuditLog, error)

	// QueryLastByModelIDFunc mocks the QueryLastByModelID method.
	QueryLastByModelIDFunc func(ctx context.Context, modelType string, modelID string) (auditlog.AuditLog, error)

	// QueryModelByVersionFunc mocks the QueryModelByVersion method.
	QueryModelByVersionFunc func(ctx context.Context, modelType string, modelID string, ver int) (auditlog.AuditLog, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, al auditlog.AuditLog) error

	// VersionsFunc mocks the Versions method.
	VersionsFunc func(ctx context.Context, modelType string, modelID string) ([]int, error)

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(tx sqlx.ExtContext) auditlog.Store

	// calls tracks calls to the methods.
	calls struct {
		// DeleteVersions holds details about calls to the DeleteVersions method.
		DeleteVersions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModelType is the modelType argument value.
			ModelType string
			// ModelID is the modelID argument value.
			ModelID string
			// Versions is the versions argument value.
			Versions []int
		}
		// OverThreshold holds details about calls to the OverThreshold method.
		OverThreshold []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Threshold is the threshold argument value.
			Threshold int
			// Limit is the limit argument value.
			Limit int
		}
		// QueryHistoryByModelID holds details about calls to the QueryHistoryByModelID method.
		QueryHistoryByModelID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModelType is the modelType argument value.
			ModelType string
			// ModelID is the modelID argument value.
			ModelID string
		}
		// QueryLastByModelID holds details about calls to the QueryLastByModelID method.
		QueryLastByModelID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModelType is the modelType argument value.
			ModelType string
			// ModelID is the modelID argument value.
			ModelID string
		}
		// QueryModelByVersion holds details about calls to the QueryModelByVersion method.
		QueryModelByVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModelType is the modelType argument value.
			ModelType string
			// ModelID is the modelID argument value.
			ModelID string
			// Ver is the ver argument value.
			Ver int
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Al is the al argument value.
			Al auditlog.AuditLog
		}
		// Versions holds details about calls to the Versions method.
		Versions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModelType is the modelType argument value.
			ModelType string
			// ModelID is the modelID argument value.
			ModelID string
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Tx is the tx argument value.
			Tx sqlx.ExtContext
		}
	}
	lockDeleteVersions        sync.RWMutex
	lockOverThreshold         sync.RWMutex
	lockQueryHistoryByModelID sync.RWMutex
	lockQueryLastByModelID    sync.RWMutex
	lockQueryModelByVersion   sync.RWMutex
	lockSave                  sync.RWMutex
	lockVersions              sync.RWMutex
	lockWithTx                sync.RWMutex
}

// DeleteVersions calls DeleteVersionsFunc.
func (mock *StoreMock) DeleteVersions(ctx context.Context, modelType string, modelID string, versions []int) (int, error) {
	if mock.DeleteVersionsFunc == nil {
		panic("StoreMock.DeleteVersionsFunc: method is nil but Store.DeleteVersions was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
		Versions  []int
	}{
		Ctx:       ctx,
		ModelType: modelType,
		ModelID:   modelID,
		Versions:  versions,
	}
	mock.lockDeleteVersions.Lock()
	mock.calls.DeleteVersions = append(mock.calls.DeleteVersions, callInfo)
	mock.lockDeleteVersions.Unlock()
	return mock.DeleteVersionsFunc(ctx, modelType, modelID, versions)
}

// DeleteVersionsCalls gets all the calls that were made to DeleteVersions.
// Check the length with:
//
//	len(mockedStore.DeleteVersionsCalls())
func (mock *StoreMock) DeleteVersionsCalls() []struct {
	Ctx       context.Context
	ModelType string
	ModelID   string
	Versions  []int
} {
	var calls []struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
		Versions  []int
	}
	mock.lockDeleteVersions.RLock()
	calls = mock.calls.DeleteVersions
	mock.lockDeleteVersions.RUnlock()
	return calls
}

// OverThreshold calls OverThresholdFunc.
func (mock *StoreMock) OverThreshold(ctx context.Context, threshold int, limit int) ([]auditlog.ModelRef, error) {
	if mock.OverThresholdFunc == nil {
		panic("StoreMock.OverThresholdFunc: method is nil but Store.OverThreshold was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Threshold int
		Limit     int
	}{
		Ctx:       ctx,
		Threshold: threshold,
		Limit:     limit,
	}
	mock.lockOverThreshold.Lock()
	mock.calls.OverThreshold = append(mock.calls.OverThreshold, callInfo)
	mock.lockOverThreshold.Unlock()
	return mock.OverThresholdFunc(ctx, threshold, limit)
}

// OverThresholdCalls gets all the calls that were made to OverThreshold.
// Check the length with:
//
//	len(mockedStore.OverThresholdCalls())
func (mock *StoreMock) OverThresholdCalls() []struct {
	Ctx       context.Context
	Threshold int
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		Threshold int
		Limit     int
	}
	mock.lockOverThreshold.RLock()
	calls = mock.calls.OverThreshold
	mock.lockOverThreshold.RUnlock()
	return calls
}

// QueryHistoryByModelID calls QueryHistoryByModelIDFunc.
func (mock *StoreMock) QueryHistoryByModelID(ctx context.Context, modelType string, modelID string) ([]auditlog.AuditLog, error) {
	if mock.QueryHistoryByModelIDFunc == nil {
		panic("StoreMock.QueryHistoryByModelIDFunc: method is nil but Store.QueryHistoryByModelID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
	}{
		Ctx:       ctx,
		ModelType: modelType,
		ModelID:   modelID,
	}
	mock.lockQueryHistoryByModelID.Lock()
	mock.calls.QueryHistoryByModelID = append(mock.calls.QueryHistoryByModelID, callInfo)
	mock.lockQueryHistoryByModelID.Unlock()
	return mock.QueryHistoryByModelIDFunc(ctx, modelType, modelID)
}

// QueryHistoryByModelIDCalls gets all the calls that were made to QueryHistoryByModelID.
// Check the length with:
//
//	len(mockedStore.QueryHistoryByModelIDCalls())
func (mock *StoreMock) QueryHistoryByModelIDCalls() []struct {
	Ctx       context.Context
	ModelType string
	ModelID   string
} {
	var calls []struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
	}
	mock.lockQueryHistoryByModelID.RLock()
	calls = mock.calls.QueryHistoryByModelID
	mock.lockQueryHistoryByModelID.RUnlock()
	return calls
}

// QueryLastByModelID calls QueryLastByModelIDFunc.
func (mock *StoreMock) QueryLastByModelID(ctx context.Context, modelType string, modelID string) (auditlog.AuditLog, error) {
	if mock.QueryLastByModelIDFunc == nil {
		panic("StoreMock.QueryLastByModelIDFunc: method is nil but Store.QueryLastByModelID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
	}{
		Ctx:       ctx,
		ModelType: modelType,
		ModelID:   modelID,
	}
	mock.lockQueryLastByModelID.Lock()
	mock.calls.QueryLastByModelID = append(mock.calls.QueryLastByModelID, callInfo)
	mock.lockQueryLastByModelID.Unlock()
	return mock.QueryLastByModelIDFunc(ctx, modelType, modelID)
}

// QueryLastByModelIDCalls gets all the calls that were made to QueryLastByModelID.
// Check the length with:
//
//	len(mockedStore.QueryLastByModelIDCalls())
func (mock *StoreMock) QueryLastByModelIDCalls() []struct {
	Ctx       context.Context
	ModelType string
	ModelID   string
} {
	var calls []struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
	}
	mock.lockQueryLastByModelID.RLock()
	calls = mock.calls.QueryLastByModelID
	mock.lockQueryLastByModelID.RUnlock()
	return calls
}

// QueryModelByVersion calls QueryModelByVersionFunc.
func (mock *StoreMock) QueryModelByVersion(ctx context.Context, modelType string, modelID string, ver int) (auditlog.AuditLog, error) {
	if mock.QueryModelByVersionFunc == nil {
		panic("StoreMock.QueryModelByVersionFunc: method is nil but Store.QueryModelByVersion was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
		Ver       int
	}{
		Ctx:       ctx,
		ModelType: modelType,
		ModelID:   modelID,
		Ver:       ver,
	}
	mock.lockQueryModelByVersion.Lock()
	mock.calls.QueryModelByVersion = append(mock.calls.QueryModelByVersion, callInfo)
	mock.lockQueryModelByVersion.Unlock()
	return mock.QueryModelByVersionFunc(ctx, modelType, modelID, ver)
}

// QueryModelByVersionCalls gets all the calls that were made to QueryModelByVersion.
// Check the length with:
//
//	len(mockedStore.QueryModelByVersionCalls())
func (mock *StoreMock) QueryModelByVersionCalls() []struct {
	Ctx       context.Context
	ModelType string
	ModelID   string
	Ver       int
} {
	var calls []struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
		Ver       int
	}
	mock.lockQueryModelByVersion.RLock()
	calls = mock.calls.QueryModelByVersion
	mock.lockQueryModelByVersion.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *StoreMock) Save(ctx context.Context, al auditlog.AuditLog) error {
	if mock.SaveFunc == nil {
		panic("StoreMock.SaveFunc: method is nil but Store.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Al  auditlog.AuditLog
	}{
		Ctx: ctx,
		Al:  al,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, al)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedStore.SaveCalls())
func (mock *StoreMock) SaveCalls() []struct {
	Ctx context.Context
	Al  auditlog.AuditLog
} {
	var calls []struct {
		Ctx context.Context
		Al  auditlog.AuditLog
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Versions calls VersionsFunc.
func (mock *StoreMock) Versions(ctx context.Context, modelType string, modelID string) ([]int, error) {
	if mock.VersionsFunc == nil {
		panic("StoreMock.VersionsFunc: method is nil but Store.Versions was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
	}{
		Ctx:       ctx,
		ModelType: modelType,
		ModelID:   modelID,
	}
	mock.lockVersions.Lock()
	mock.calls.Versions = append(mock.calls.Versions, callInfo)
	mock.lockVersions.Unlock()
	return mock.VersionsFunc(ctx, modelType, modelID)
}

// VersionsCalls gets all the calls that were made to Versions.
// Check the length with:
//
//	len(mockedStore.VersionsCalls())
func (mock *StoreMock) VersionsCalls() []struct {
	Ctx       context.Context
	ModelType string
	ModelID   string
} {
	var calls []struct {
		Ctx       context.Context
		ModelType string
		ModelID   string
	}
	mock.lockVersions.RLock()
	calls = mock.calls.Versions
	mock.lockVersions.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *StoreMock) WithTx(tx sqlx.ExtContext) auditlog.Store {
	if mock.WithTxFunc == nil {
		panic("StoreMock.WithTxFunc: method is nil but Store.WithTx was just called")
	}
	callInfo := struct {
		Tx sqlx.ExtContext
	}{
		Tx: tx,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(tx)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedStore.WithTxCalls())
func (mock *StoreMock) WithTxCalls() []struct {
	Tx sqlx.ExtContext
} {
	var calls []struct {
		Tx sqlx.ExtContext
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
